default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: db

development:
  <<: *default
  username: hogehoge
  password: fasjkdl29
  database: docker_development

production:
  <<: *default
  database: docker_production
  username: docker
  password: <%= ENV['DOCKER_DATABASE_PASSWORD'] %>
